if(instance_exists(obj_Players)){
	x = (obj_Players.x - 490);
	y = (obj_Players.y - 350);

if(obj_Players.manaPoints >= 100){
	energy1.visible = true;
	energy2.visible = true;
	energy3.visible = true;
	energy4.visible = true;
	energy5.visible = true;
	energy6.visible = true;
	energy7.visible = true;
	energy8.visible = true;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
}

if(obj_Players.manaPoints < 100){
	if(obj_Players.manaPoints >= 95){
	energy1.visible = false;
	energy2.visible = true;
	energy3.visible = true;
	energy4.visible = true;
	energy5.visible = true;
	energy6.visible = true;
	energy7.visible = true;
	energy8.visible = true;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 95){
	if(obj_Players.manaPoints >= 90){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = true;
	energy4.visible = true;
	energy5.visible = true;
	energy6.visible = true;
	energy7.visible = true;
	energy8.visible = true;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 90){
	if(obj_Players.manaPoints >= 85){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = true;
	energy5.visible = true;
	energy6.visible = true;
	energy7.visible = true;
	energy8.visible = true;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 85){
	if(obj_Players.manaPoints >= 80){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = true;
	energy6.visible = true;
	energy7.visible = true;
	energy8.visible = true;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 80){
	if(obj_Players.manaPoints >= 75){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = true;
	energy7.visible = true;
	energy8.visible = true;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 75){
	if(obj_Players.manaPoints >= 70){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = true;
	energy8.visible = true;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 70){
	if(obj_Players.manaPoints >= 65){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = true;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 65){
	if(obj_Players.manaPoints >= 60){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = true;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 60){
	if(obj_Players.manaPoints >= 55){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = true;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 55){
	if(obj_Players.manaPoints >= 50){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = true;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 50){
	if(obj_Players.manaPoints >= 45){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = true;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 45){
	if(obj_Players.manaPoints >= 40){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = true;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 40){
	if(obj_Players.manaPoints >= 35){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = false;
	energy14.visible = true;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 35){
	if(obj_Players.manaPoints >= 30){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = false;
	energy14.visible = false;
	energy15.visible = true;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 30){
	if(obj_Players.manaPoints >= 25){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = false;
	energy14.visible = false;
	energy15.visible = false;
	energy16.visible = true;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 25){
	if(obj_Players.manaPoints >= 20){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = false;
	energy14.visible = false;
	energy15.visible = false;
	energy16.visible = false;
	energy17.visible = true;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 20){
	if(obj_Players.manaPoints >= 15){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = false;
	energy14.visible = false;
	energy15.visible = false;
	energy16.visible = false;
	energy17.visible = false;
	energy18.visible = true;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 15){
	if(obj_Players.manaPoints >= 10){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = false;
	energy14.visible = false;
	energy15.visible = false;
	energy16.visible = false;
	energy17.visible = false;
	energy18.visible = false;
	energy19.visible = true;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints < 10){
	if(obj_Players.manaPoints >= 5){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = false;
	energy14.visible = false;
	energy15.visible = false;
	energy16.visible = false;
	energy17.visible = false;
	energy18.visible = false;
	energy19.visible = false;
	energy20.visible = true;
	}
}
if(obj_Players.manaPoints <= 0){
	energy1.visible = false;
	energy2.visible = false;
	energy3.visible = false;
	energy4.visible = false;
	energy5.visible = false;
	energy6.visible = false;
	energy7.visible = false;
	energy8.visible = false;
	energy9.visible = false;
	energy10.visible = false;
	energy11.visible = false;
	energy12.visible = false;
	energy13.visible = false;
	energy14.visible = false;
	energy15.visible = false;
	energy16.visible = false;
	energy17.visible = false;
	energy18.visible = false;
	energy19.visible = false;
	energy20.visible = false;
}
}
