if(instance_exists(obj_Players)){
	x = (obj_Players.x - 450);
	y = (obj_Players.y - 350);
	

if(obj_Players.healthPoints >= 100){
	instance1.visible = true;
	instance2.visible = true;
	instance3.visible = true;
	instance4.visible = true;
	instance5.visible = true;
	instance6.visible = true;
	instance7.visible = true;
	instance8.visible = true;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 95){
	instance1.visible = false;
	instance2.visible = true;
	instance3.visible = true;
	instance4.visible = true;
	instance5.visible = true;
	instance6.visible = true;
	instance7.visible = true;
	instance8.visible = true;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 90){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = true;
	instance4.visible = true;
	instance5.visible = true;
	instance6.visible = true;
	instance7.visible = true;
	instance8.visible = true;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 85){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = true;
	instance5.visible = true;
	instance6.visible = true;
	instance7.visible = true;
	instance8.visible = true;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 80){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = true;
	instance6.visible = true;
	instance7.visible = true;
	instance8.visible = true;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 75){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = true;
	instance7.visible = true;
	instance8.visible = true;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;

}
else if(obj_Players.healthPoints >= 70){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = true;
	instance8.visible = true;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 65){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = true;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 60){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = true;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 55){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = true;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 50){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = true;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 45){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = true;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 40){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = false;
	instance13.visible = true;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 35){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = false;
	instance13.visible = false;
	instance14.visible = true;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;

}
else if(obj_Players.healthPoints >= 30){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = false;
	instance13.visible = false;
	instance14.visible = false;
	instance15.visible = true;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 25){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = false;
	instance13.visible = false;
	instance14.visible = false;
	instance15.visible = false;
	instance16.visible = true;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 20){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = false;
	instance13.visible = false;
	instance14.visible = false;
	instance15.visible = false;
	instance16.visible = false;
	instance17.visible = true;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 15){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = false;
	instance13.visible = false;
	instance14.visible = false;
	instance15.visible = false;
	instance16.visible = false;
	instance17.visible = false;
	instance18.visible = true;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 10){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = false;
	instance13.visible = false;
	instance14.visible = false;
	instance15.visible = false;
	instance16.visible = false;
	instance17.visible = false;
	instance18.visible = false;
	instance19.visible = true;
}
else if(obj_Players.healthPoints >= 5){
	instance1.visible = false;
	instance2.visible = false;
	instance3.visible = false;
	instance4.visible = false;
	instance5.visible = false;
	instance6.visible = false;
	instance7.visible = false;
	instance8.visible = false;
	instance9.visible = false;
	instance10.visible = false;
	instance11.visible = false;
	instance12.visible = false;
	instance13.visible = false;
	instance14.visible = false;
	instance15.visible = false;
	instance16.visible = false;
	instance17.visible = false;
	instance18.visible = false;
	instance19.visible = false;
}

}
